fastlane_version "2.22.0"

default_platform :ios


platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    cert
    sigh(force: true)
    gym(scheme: 'NatalChartsApp - Release', use_legacy_build_api: true)

    emails = values[:test_email] ? values[:test_email] : ['hi@kasra.codes'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'c632577cff3855aa1a09f657e44d98ecf96cc9fc',
             build_secret: 'b8a8d85e8fc0c4024fcc76fc3f7aadc04c99a178bb3987f40f89db01e7e8a9d6',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
